// Usage Quota — build script
// 1) copy src/host.js -> lib/index.js（ESM host 插件）
// 2) wrap src/client-bundle.js -> lib/client.js（client-modules 经典脚本 bundle）
//    包装形态与官方 client 包一致：window.__ModuleLoader__.load({ id, factory })
// 用法：node scripts/build.mjs（package.json build/prepack 均调用）
import { mkdir, readFile, rm, writeFile } from 'node:fs/promises'
import { dirname, join } from 'node:path'
import { fileURLToPath } from 'node:url'

const root = dirname(fileURLToPath(new URL('../package.json', import.meta.url)))
const libDir = join(root, 'lib')

await rm(libDir, { recursive: true, force: true })
await mkdir(libDir, { recursive: true })

// 1) host（ESM，原样复制，加文件头注释）
const hostSource = await readFile(join(root, 'src', 'host.js'), 'utf8')
await writeFile(join(libDir, 'index.js'), `// Generated by scripts/build.mjs from src/host.js — do not edit directly.\n${hostSource}`)

// 2) client（CJS 模块源 → __ModuleLoader__ bundle）
const clientSource = await readFile(join(root, 'src', 'client-bundle.js'), 'utf8')
const wrapped = [
  'window.__ModuleLoader__.load({ id: "dsh-usage-quota", factory: (require) => {',
  'var module = { exports: {} }; var exports = module.exports;',
  clientSource,
  'return module.exports;',
  '} });',
  '',
].join('\n')
await writeFile(join(libDir, 'client.js'), wrapped)

console.log('build OK → lib/index.js, lib/client.js')
