// dsh-idelike — build script
// 1) copy src/host.js -> lib/index.js（ESM host 插件）
// 2) 若存在 node_modules/highlight.js，则把它的 CommonJS 源码打包成浏览器单文件 bundle
//    （window.hljs）；否则回退到 vendor/highlight.min.js；再否则跳过（客户端用内置轻量高亮）
// 3) wrap src/client-bundle.js -> lib/client.js（client-modules 经典脚本 bundle）
//    包装形态与官方 client 包一致：window.__ModuleLoader__.load({ id, factory })
// 用法：node scripts/build.mjs（package.json build 调用）
import { mkdir, readFile, readdir, rm, stat, writeFile } from 'node:fs/promises'
import { dirname, join } from 'node:path'
import { fileURLToPath } from 'node:url'

const root = dirname(fileURLToPath(new URL('../package.json', import.meta.url)))
const libDir = join(root, 'lib')

await rm(libDir, { recursive: true, force: true })
await mkdir(libDir, { recursive: true })

// 1) host（ESM，原样复制，加文件头注释）
const hostSource = await readFile(join(root, 'src', 'host.js'), 'utf8')
await writeFile(join(libDir, 'index.js'), `// Generated by scripts/build.mjs from src/host.js — do not edit directly.\n${hostSource}`)

// 2) highlight.js（可选）：把 CommonJS 源码打包成设置 window.hljs 的 IIFE
const hljsSource = await bundleHighlightJs(root)

// 3) client（CJS 模块源 → __ModuleLoader__ bundle）
const clientSource = await readFile(join(root, 'src', 'client-bundle.js'), 'utf8')
const wrapped = [
  'window.__ModuleLoader__.load({ id: "dsh-idelike", factory: (require) => {',
  'var module = { exports: {} }; var exports = module.exports;',
  hljsSource,
  clientSource,
  'return module.exports;',
  '} });',
  '',
].join('\n')
await writeFile(join(libDir, 'client.js'), wrapped)

console.log('build OK → lib/index.js, lib/client.js')

async function fileExists(p) {
  try { return (await stat(p)).isFile() } catch (err) { return false }
}

async function bundleHighlightJs(pluginRoot) {
  // 候选 node_modules/highlight.js/lib 路径（插件自身 → 项目根）
  const candidates = [
    join(pluginRoot, 'node_modules', 'highlight.js', 'lib'),
    join(pluginRoot, '..', '..', '..', 'node_modules', 'highlight.js', 'lib'),
  ]
  let lib = null
  for (const c of candidates) {
    if (await fileExists(join(c, 'core.js')) && await fileExists(join(c, 'common.js'))) { lib = c; break }
  }

  // 兜底：pnpm 的虚拟仓库 node_modules/.pnpm 里找 highlight.js@*
  if (!lib) {
    const pnpmDir = join(pluginRoot, '..', '..', '..', 'node_modules', '.pnpm')
    try {
      for (const e of await readdir(pnpmDir)) {
        if (e.indexOf('highlight.js@') !== 0) continue
        const c = join(pnpmDir, e, 'node_modules', 'highlight.js', 'lib')
        if (await fileExists(join(c, 'core.js')) && await fileExists(join(c, 'common.js'))) { lib = c; break }
      }
    } catch (err) { /* .pnpm 不存在则忽略 */ }
  }

  if (lib) {
    try {
      const coreSource = await readFile(join(lib, 'core.js'), 'utf8')
      const commonSource = await readFile(join(lib, 'common.js'), 'utf8')
      const langNames = [...commonSource.matchAll(/require\('\.\/languages\/([a-z0-9-]+)'\)/g)].map(m => m[1])

      const modules = []
      modules.push(`'./core': function (module, exports, require) {\n${coreSource}\n},`)
      for (const name of langNames) {
        const src = await readFile(join(lib, 'languages', name + '.js'), 'utf8')
        modules.push(`'./languages/${name}': function (module, exports, require) {\n${src}\n},`)
      }
      const registerCalls = langNames.map(n => `hljs.registerLanguage('${n}', require('./languages/${n}'));`).join('\n')

      const bundle = [
        '(function () {',
        'var modules = {',
        modules.join('\n'),
        '};',
        'var cache = {};',
        'function require(id) {',
        '  if (cache[id]) return cache[id].exports;',
        '  var module = cache[id] = { exports: {} };',
        '  modules[id](module, module.exports, require);',
        '  return module.exports;',
        '}',
        'var hljs = require("./core");',
        registerCalls,
        'hljs.HighlightJS = hljs;',
        'hljs.default = hljs;',
        'window.hljs = hljs;',
        '})();',
      ].join('\n')

      console.log(`  ✓ 已从 node_modules/highlight.js 打包高亮 bundle（${langNames.length} 种语言）`)
      return bundle
    } catch (err) {
      console.log('  ✗ 从 node_modules/highlight.js 打包失败：' + String((err && err.message) || err))
    }
  }

  // 回退：vendor/highlight.min.js（手动放置的浏览器版）
  if (await fileExists(join(pluginRoot, 'vendor', 'highlight.min.js'))) {
    const vendor = await readFile(join(pluginRoot, 'vendor', 'highlight.min.js'), 'utf8')
    if (vendor.trim().length > 0) {
      console.log('  ✓ 使用 vendor/highlight.min.js')
      return vendor
    }
  }

  console.log('  提示：未找到 highlight.js，语法高亮将回退到内置轻量正则')
  return ''
}
